### PR TITLE
Create .ignore

### PR DESCRIPTION
**Pull request by stereohorse**

### CODE REVIEW

**Comment by github-bot-qadojo** [comment]
test

**Comment by stereohorse** [comment]
test

**Comment by stereohorse** [comment]
test2

**Comment by github-bot-qadojo** [comment]
Can one of the admins verify this patch?

**Comment by stereohorse** [comment]
ok to test

**Comment by github-bot-qadojo** [comment]
ok to test

**Comment by stereohorse** [comment]
test

**Comment by stereohorse** [comment]
test

**Comment by github-bot-qadojo** [comment]
test

**Comment by stereohorse** [comment]
t

**Comment by github-bot-qadojo** [comment]
Build failed

**Comment by stereohorse** [comment]
check please

**Comment by github-bot-qadojo** [comment]
Successfully built

**Comment by github-bot-qadojo** [comment]
Successfully built

**Comment by stereohorse** [comment]
test

**Pull request closed without merging**
